name       : kcalcore
version    : 19.08.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kcalcore-19.08.0.tar.xz : 7c7bbca70ada8c8317d6d3d91e0357b2b5886328189423e0b7fac1d326f8ed85
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
