name       : kcalcore
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kcalcore-17.08.3.tar.xz : 050ee3c9abafef2f668276d9456e9fdbe4be7625572a8f3e93f073963f6fc647
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(uuid)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
