name       : kcalcore
version    : 19.04.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kcalcore-19.04.0.tar.xz : 0cdcfebabb9af96650b71ba6361a4557df35144f0b1041f004bff7510c6334b2
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
