name       : kcalcore
version    : 19.08.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kcalcore-19.08.1.tar.xz : 8c1bbd8e7673907de2c3682cbc1c4fe4a165cbe0b9a2fe399c4b0ae73894228a
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
