name       : kcalcore
version    : 18.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kcalcore-18.04.3.tar.xz : f2df15f6d60c6a95862a98ec50de4dbc311c4f6e0157982dbf15aa5646454fd0
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
