name       : kcalcore
version    : 18.04.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kcalcore-18.04.2.tar.xz : 61485fc9643fe383e8b76631db5bd1cb7e03ba8357502ec0c3652f15f7ec342a
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
