name       : kcalcore
version    : 18.08.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kcalcore-18.08.2.tar.xz : a70ea203e35188185fa06066ea6f7edc7886d3c4ad8d91d6b2e1a980d4cc3d86
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
