name       : kcalcore
version    : 18.12.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kcalcore-18.12.3.tar.xz : d6d6ce1bbdea4eac352b74bcc4bee77da107fdbafab47440b6be5fc3f9d90452
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
