name       : kcalcore
version    : 18.12.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kcalcore-18.12.0.tar.xz : 90c00b359154f8296ed5edff0b14f2bfd522382c39c5e61547e92fd6725bc713
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
