name       : kcalcore
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kcalcore-17.04.0.tar.xz : 40b27b562c2cead0f8960e10a3116540f6258d3d2d44aa88cc18fc3a1d80ba76
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
