name       : kcalcore
version    : 17.04.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kcalcore-17.04.1.tar.xz : fa18546039e8e9ac262ca149ffe0ab842e40ee219a9cd6d8f67fab1da7c7842e
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
