name       : kcalcore
version    : 18.08.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kcalcore-18.08.1.tar.xz : 563239f2bfc7c4727add80f621781917a1f280c545c4e19d8e98a68a6b14c94d
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
