name       : kcalcore
version    : 18.04.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kcalcore-18.04.0.tar.xz : 55ec98418c571f8dd0874c2ac46d660d4d2aee1b1a66b34370c447eb0fa98f3c
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
