name       : kcalcore
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kcalcore-17.08.1.tar.xz : fcea7b6ff4c023b7f921fb79331bdb86314721fdfbf663a5a6066a4d01918f20
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports
    the standard formats iCalendar and vCalendar and the group scheduling standard
    iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(uuid)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
