name       : kcalcore
version    : 17.12.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kcalcore-17.12.3.tar.xz : 7f80fcbbeea8d349327f4bba6241d348e9b159242b0686a9a97c99fb466bb888
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports
    the standard formats iCalendar and vCalendar and the group scheduling standard
    iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
