name       : kcalcore
version    : 17.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kcalcore-17.12.2.tar.xz : 4724febba0434efa5c8b0f72087b6d86e534ac5a0c0a1afa2fe75fa440ebe71b
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
